# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

#pool:
#  vmImage: Windows-latest

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(build.sourcesdirectory)/
      git remote add originTest1 https://%SYSTEM_ACCESSTOKEN%@dev.azure.com/SahithK/DueDate/_git/Test123 -Force
      git push -u originTest1  --all -Force
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
